services:
  client:
    build: 
      context: ./client-hexagonal
      dockerfile: Dockerfile # If is dev use Dockerfile.dev
    container_name: client
    restart: unless-stopped
    volumes: # If is dev uncomment this block
      - './client:/app'
      - '/app/node_modules'
    ports:
      - '5173:5173'
    depends_on:
      - api
    env_file:
      - ./client-hexagonal/.env
    networks:
      - grafana_network

  api:
    build: ./api
    container_name: api
    restart: unless-stopped
    ports: # If is dev uncomment this block
      - '8000:8000'
    depends_on:
      - mongo
    env_file:
      - ./api/.env
    networks:
      - grafana_network

  grafana:
    build: ./grafana
    container_name: grafana
    restart: unless-stopped
    environment:
      - TERM=linux
      - GF_INSTALL_PLUGINS=grafana-clock-panel,grafana-polystat-panel,grafana-mongodb-datasource
    ports:
      - '3000:3000'
    volumes:
      - 'grafana_storage:/var/lib/grafana'
    depends_on:
      - mongo
    networks:
      - grafana_network

  mongo:
    image: mongo:latest
    container_name: mongo
    restart: unless-stopped
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    ports:
      - '27017:27017'
    volumes:
      - 'mongo_data:/data/db'
    networks:
      - grafana_network

  nginx:
    build: ./nginx
    ports:
      - "80:80"
    depends_on:
      - client
      - api
    networks:
      - grafana_network

volumes:
  grafana_storage: {}
  mongo_data: {}

networks:
  grafana_network: